version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cybercafe_db
    restart: always
    environment:
      POSTGRES_USER: cyberadmin
      POSTGRES_PASSWORD: cyberpassword123
      POSTGRES_DB: cybercafe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cybercafe_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cybercafe_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://cyberadmin:cyberpassword123@postgres:5432/cybercafe_db?schema=public"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "cybercafe_super_secret_jwt_key_2026"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: cybercafe_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cybercafe_frontend
    restart: always

volumes:
  postgres_data:
